# Generated by Django 4.2.16 on 2024-10-07 05:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144', '144p'), ('360', '360p'), ('480', '480p'), ('720', '720p'), ('1080', '1080p')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
