# Generated by Django 4.2.16 on 2024-10-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_movie_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
