# Generated by Django 4.2.16 on 2024-10-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielanguages',
            old_name='languages',
            new_name='movie_languages',
        ),
    ]
